### ISSUE TITLE
无法正常播放

### ISSUE THREAD

**Issue by foxru1982** [whitebrise/BlurayPoster#1]
我按照教程安装好后，emby可以看到blurayposter这个播放端，oppo里面也可以看到OPPO的app标志在屏幕之间间歇性显示，但是点击播放没有任何反应，不知道问题出在什么地方，另外config文件中“tv”命令行是否可以删除，大部分用蓝光机的朋友应该更希望使用ipad来直接操作emby。

**Comment by whitebrise** [comment]
不想用tv控制的可以把tv部分的配置整体删除，你把配置中log_level改为debug，然后再点一次海报墙，再把你的配置文件(账号和密码信息码掉)和运行时的日志发上来

**Comment by foxru1982** [comment]
[config.json](https://github.com/user-attachments/files/16335444/config.json)

**Comment by whitebrise** [comment]
哪里装都行，这个没有要求。看日志你是映射地址配置错了，你的emby媒体库配的目录是/volume6/系列电影/007系列...开头的，但你配置文件里的是/MediaCenter，贴一下你的emby媒体库文件夹的设置，以及你oppo播放器用遥控器操作时实际的路径图

**Comment by whitebrise** [comment]
![Snipaste_2024-07-22_23-22-10](https://github.com/user-attachments/assets/4f7fac62-eff1-40c7-bf1c-bb648d59399b)
media的路径指的是这个路径，你的media路径是错的

**Comment by whitebrise** [comment]
你用oppo选片的时候，用nfs应该是192.168.2.88 -> xx -> xxx，把后面的路径也说一下，我好判断你的实际映射路径应该怎么配

**Comment by foxru1982** [comment]
因为我有多个视频文件夹，所以nfs选片是192.168.2.88》视频》欧美电影（4K） 或者192.168.2.88》视频》亚洲电影，另外我把oppo选片和emby的媒体库路径图片也一并上传
![微信图片_20240723082939](https://github.com/user-attachments/assets/bae317ce-f3d2-44e9-90e1-002c44352ae1)
![微信图片_20240723082949](https://github.com/user-attachments/assets/1ac27129-9704-4f2e-b36e-70b6f6554821)

**Comment by whitebrise** [comment]
你是用nfs的吗？用nfs的话把oppo的那个界面的192.168.2.88的那个界面点开，我看看后面一级目录是啥

**Comment by whitebrise** [comment]
> 因为我有多个视频文件夹，所以nfs选片是192.168.2.88》视频》欧美电影（4K） 或者192.168.2.88》视频》亚洲电影，另外我把oppo选片和emby的媒体库路径图片也一并上传 ![微信图片_20240723082939](https://private-user-images.githubusercontent.com/138606826/351147193-bae317ce-f3d2-44e9-90e1-002c44352ae1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MTIxODYsIm5iZiI6MTcyMTcxMTg4NiwicGF0aCI6Ii8xMzg2MDY4MjYvMzUxMTQ3MTkzLWJhZTMxN2NlLWYzZDItNDRlOS05MGUxLTAwMmM0NDM1MmFlMS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyM1QwNTE4MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NjYxMjQyMmY0Mzk0NGJhY2RiYmE1MjdhYWUxNjRiZDYwNjU1MDQ2OTFlMzc4NTc0ZGRmNTdlMDJkNjJmNjk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EKVWgQJDEnAnrktIIKpYvZUmNGHrAJKT4G6x9ysEd5Q) ![微信图片_20240723082949](https://private-user-images.githubusercontent.com/138606826/351147203-1ac27129-9704-4f2e-b36e-70b6f6554821.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MTIxODYsIm5iZiI6MTcyMTcxMTg4NiwicGF0aCI6Ii8xMzg2MDY4MjYvMzUxMTQ3MjAzLTFhYzI3MTI5LTk3MDQtNGYyZS1iMzZlLTcwYjZmNjU1NDgyMS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyM1QwNTE4MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYWUxMGVkNWRhZDIwM2YxMzYyMDUzMmYzNjk2ZTNkNWE1ZjNmNzczMGQzMmUwMjU1MjM1MDdkZTAxYWQyMzI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aIRv6GcBD980i9g1_nwcEmPjBGMphGo-L51VqGF84qY)

oppo里192.168.2.88后面点开，中间应该还有一级目录叫volume1(或者volume2)这种的吧？

**Comment by foxru1982** [comment]
没有volumeX 这一级

**Comment by whitebrise** [comment]
首先，docker或者代码要拉最新的

然后，没有volumeX这一级的话，你需要这么配目录
"Media": "/volume1", "SMB": "", "NFS": "/192.168.2.88"

**Comment by whitebrise** [comment]
首先，docker或者代码要拉最新的

然后，没有volumeX这一级的话，你需要这么配目录
"MappingPath": [
      {
        "Media": "/volume1",
        "SMB": "",
        "NFS": "/192.168.2.88"
      },
  {
        "Media": "/volume2",
        "SMB": "",
        "NFS": "/192.168.2.88"
      }
    ]

像这样，把你的volume xxx都配完，配完记得检查一下json格式，然后重启就行了

**Comment by foxru1982** [comment]
还是不行 配置完 json检查了没问题 我把完整的路径图片发上来 还有新的日志 麻烦大佬再看一下
/
[blurayposter (1).html.zip](https://github.com/user-attachments/files/16348966/blurayposter.1.html.zip)
![WechatIMG28](https://github.com/user-attachments/assets/f8381909-2b16-4d34-a0f3-6fefa49d0c1b)
![WechatIMG29](https://github.com/user-attachments/assets/50878f25-8e56-4f6c-91ab-b01551121ff2)
![WechatIMG30](https://github.com/user-attachments/assets/19bf24bb-0794-4126-b82f-7d9dd2549ae3)

**Comment by whitebrise** [comment]
感觉有点奇怪，是你的文件夹名就叫"volume1\文档资料"？文件夹名里怎么有"/" "\"这种符号？如果是的话，换"-", "_"这种都行啊，"/" "\"这种在命名里会有很多问题的

**Comment by whitebrise** [comment]
感觉有点奇怪，是你的文件夹名就叫"volume1\文档资料"？文件夹名里怎么有"/" "\\"这种符号？如果是的话，换"-", "_"这种都行啊，"/" "\\"这种在命名里会有很多问题的

**Comment by whitebrise** [comment]
感觉有点奇怪，是你的文件夹名字就叫"volume1\文档资料"？文件夹名字里怎么有"/" "\\"这种符号？这种斜线符号在很多文件系统里的命名属于非法字符。如果是的话，换"-", "_"这种分隔都行啊，"/" "\\"这种在命名里会有很多问题的

**Comment by foxru1982** [comment]
文件夹名字是文档资料  volume1\文档资料 是OPPO203直接从上面一步视频点进来以后的显示

**Comment by whitebrise** [comment]
那就奇怪了，你既然进入说volume1是上一步进入的界面，那说明你现在在volume1文件夹里面，那怎么会显示volume2, volume3的路径?

**Comment by foxru1982** [comment]
私信了
