### ISSUE TITLE
不能播放， 无反应，无错误日志

### ISSUE THREAD

**Issue by jheroy** [whitebrise/BlurayPoster#2]
Starting the main application
Configuration for AV not found or incomplete.
Media operations completed successfully
Starting new HTTP connection (1): 10.0.1.4:8096
http://10.0.1.4:8096 "POST /emby/Users/AuthenticateByName HTTP/11" 200 1198
Login successful
Starting new HTTP connection (1): 10.0.1.4:8096
http://10.0.1.4:8096 "POST /emby/Sessions/Capabilities/Full HTTP/11" 204 0
Device registered successfully
WebSocket thread started
Websocket connected
Emby WebSocket Connection Opened
open the oppo http success
Starting new HTTP connection (1): 10.0.1.48:436
http://10.0.1.48:436 "GET /signin?%7B%22appIconType%22%3A%201%2C%20%22appIpAddress%22%3A%20%22192.168.1.8%22%7D HTTP/11" 200 82
Starting new HTTP connection (1): 10.0.1.48:436
http://10.0.1.48:436 "GET /getdevicelist HTTP/11" 200 353
open the oppo http success
Starting new HTTP connection (1): 10.0.1.48:436
http://10.0.1.48:436 "GET /signin?%7B%22appIconType%22%3A%201%2C%20%22appIpAddress%22%3A%20%22192.168.1.8%22%7D HTTP/11" 200 82
Starting new HTTP connection (1): 10.0.1.48:436
http://10.0.1.48:436 "GET /getdevicelist HTTP/11" 200 353
Emby WebSocket Message Received: {"MessageType":"Play","MessageId":"8b9e28010ae14d738431f4df2e8b82d5","Data":{"Id":"2c77862ae50b5617030e6dda9a0a5595","ItemIds":[49018],"StartPositionTicks":0,"PlayCommand":"PlayNow","ControllingUserId":"6ba9776d5e474a61b3a27c4abe175b56"}}
open the oppo http success
Starting new HTTP connection (1): 10.0.1.48:436
http://10.0.1.48:436 "GET /signin?%7B%22appIconType%22%3A%201%2C%20%22appIpAddress%22%3A%20%22192.168.1.8%22%7D HTTP/11" 200 82
Starting new HTTP connection (1): 10.0.1.48:436
http://10.0.1.48:436 "GET /getdevicelist HTTP/11" 200 353
open the oppo http success
Starting new HTTP connection (1): 10.0.1.48:436
http://10.0.1.48:436 "GET /signin?%7B%22appIconType%22%3A%201%2C%20%22appIpAddress%22%3A%20%22192.168.1.8%22%7D HTTP/11" 200 82
Starting new HTTP connection (1): 10.0.1.48:436
http://10.0.1.48:436 "GET /getdevicelist HTTP/11" 200 353
Sending ping
open the oppo http success
Starting new HTTP connection (1): 10.0.1.48:436
http://10.0.1.48:436 "GET /signin?%7B%22appIconType%22%3A%201%2C%20%22appIpAddress%22%3A%20%22192.168.1.8%22%7D HTTP/11" 200 82
Starting new HTTP connection (1): 10.0.1.48:436
http://10.0.1.48:436 "GET /getdevicelist HTTP/11" 200 353
Sending ping
open the oppo http success
Starting new HTTP connection (1): 10.0.1.48:436
http://10.0.1.48:436 "GET /signin?%7B%22appIconType%22%3A%201%2C%20%22appIpAddress%22%3A%20%22192.168.1.8%22%7D HTTP/11" 200 82
Starting new HTTP connection (1): 10.0.1.48:436
http://10.0.1.48:436 "GET /getdevicelist HTTP/11" 200 353
Emby WebSocket Message Received: {"MessageType":"Play","MessageId":"a0af21a1ab8f4b518af8783ef68e3855","Data":{"Id":"2c77862ae50b5617030e6dda9a0a5595","ItemIds":[49018],"StartPositionTicks":0,"PlayCommand":"PlayNow","ControllingUserId":"6ba9776d5e474a61b3a27c4abe175b56"}}
open the oppo http success
Starting new HTTP connection (1): 10.0.1.48:436
http://10.0.1.48:436 "GET /signin?%7B%22appIconType%22%3A%201%2C%20%22appIpAddress%22%3A%20%22192.168.1.8%22%7D HTTP/11" 200 82
Starting new HTTP connection (1): 10.0.1.48:436
http://10.0.1.48:436 "GET /getdevicelist HTTP/11" 200 353
Emby WebSocket Message Received: {"MessageType":"Play","MessageId":"10807cea32f341cbbdb94d059517d078","Data":{"Id":"2c77862ae50b5617030e6dda9a0a5595","ItemIds":[49018],"StartPositionTicks":0,"PlayCommand":"PlayNow","ControllingUserId":"6ba9776d5e474a61b3a27c4abe175b56"}}
Sending ping
open the oppo http success
Starting new HTTP connection (1): 10.0.1.48:436
http://10.0.1.48:436 "GET /signin?%7B%22appIconType%22%3A%201%2C%20%22appIpAddress%22%3A%20%22192.168.1.8%22%7D HTTP/11" 200 82
Starting new HTTP connection (1): 10.0.1.48:436
http://10.0.1.48:436 "GET /getdevicelist HTTP/11" 200 353
Emby WebSocket Message Received: {"MessageType":"Play","MessageId":"9bf3abf348e845a580e99e05cfd9abaa","Data":{"Id":"2c77862ae50b5617030e6dda9a0a5595","ItemIds":[49018],"StartPositionTicks":0,"PlayCommand":"PlayNow","ControllingUserId":"6ba9776d5e474a61b3a27c4abe175b56"}}
Emby WebSocket Message Received: {"MessageType":"Play","MessageId":"92e0d37fed1842a790f90f0fa0ced339","Data":{"Id":"2c77862ae50b5617030e6dda9a0a5595","ItemIds":[49018],"StartPositionTicks":0,"PlayCommand":"PlayNow","ControllingUserId":"6ba9776d5e474a61b3a27c4abe175b56"}}
open the oppo http success
Starting new HTTP connection (1): 10.0.1.48:436
http://10.0.1.48:436 "GET /signin?%7B%22appIconType%22%3A%201%2C%20%22appIpAddress%22%3A%20%22192.168.1.8%22%7D HTTP/11" 200 82
Starting new HTTP connection (1): 10.0.1.48:436
http://10.0.1.48:436 "GET /getdevicelist HTTP/11" 200 353
Sending ping
Emby WebSocket Message Received: {"MessageType":"Play","MessageId":"9d9ec0f3302a41cebd8c734114e060ca","Data":{"Id":"2c77862ae50b5617030e6dda9a0a5595","ItemIds":[49018],"StartPositionTicks":0,"PlayCommand":"PlayNow","ControllingUserId":"6ba9776d5e474a61b3a27c4abe175b56"}}

**Comment by whitebrise** [comment]
你是不是右上角dlna选了串流到blurayposter了？那个不要选

**Comment by jheroy** [comment]
确实是这个问题，我以为和 xnoppo 一样。

**Comment by whitebrise** [comment]
> 确实是这个问题，我以为和 xnoppo 一样。

跟xnoppo逻辑不一样，不需要依赖dlna串流。只要路径配置正确，就可以正常调用播放器播放
